jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create GeoJSON
        run: |
          mkdir -p data
          python scripts/generate_geojson.py

      - name: Commit and push changes
        run: |
          git add data/stops_with_bus_times.geojson
          git commit -m "Generated GeoJSON with bus times"
          git push
