name: Generate GeoJSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Cambia si necesitas otra versión

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate GeoJSON
        run: |
          mkdir -p data
          python scripts/generate_geojson.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/stops.geojson
          git commit -m "Generated GeoJSON file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
