name: Generate GeoJSON

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Instalar dependencias de requirements.txt
        pip install geojson  # Asegurarse de que geojson esté instalado

    - name: Run the script to generate GeoJSON
      run: |
        mkdir -p data
        python scripts/generate_geojson.py  # Ejecutar el script

    - name: Commit generated GeoJSON file
      run: |
        git add data/stops_with_bus_times.geojson
        git commit -m "Añadir archivo de paradas con tiempos de autobús"
        git push origin main
