name: Generate GeoJSON

on:
  push:
    branches:
      - main

jobs:
  generate-geojson:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create GeoJSON
        run: |
          mkdir -p data
          python scripts/generate_geojson.py

      - name: Commit and push changes
        run: |
          git add data/stops.geojson
          git commit -m "Generated stops GeoJSON"
          git push
